apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: ingress-service
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewwrite-target: /
spec:
    rules:
        -http:
            paths:
                -path:/client.html
                 backend: 
                    serviceName:client-service
                    servicePort: 3000
                
                -path:/server.html
                 backend: 
                    serviceName:server-service
                    servicePort: 5000
                    
                -path:/worker.html
                 backend: 
                    serviceName:worker-service
                    servicePort: 9000